version: '3.9' 

services:
  go-gin-app:
    container_name: go-gin-app
    image: sunnex/go-gin:1.0.0
    build: .
    # environment:
    #   # - DATABASE_URL="host=go_db port=5432 user=postgres password=postgres dbname=go_db sslmode=disable"
    ports:
      - "8888:8888"
    networks:
      - backend
    depends_on:
      - go-gin-db
    
    
    volumes:
      - .:/app
    
  go-gin-db:
    container_name: go-gin-db
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis_app:
    container_name: redis_app
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=pass123a
    ports:
      - 6379:6379
    
    networks:
      - backend
    
  # workwebui:
  #   image: go-workwebui # Replace with the actual image and tag
  #   build: .
  #   command: ["-redis=go-redis:6379", "-ns=application_namespace", "-listen=:5040"]
  #   ports:
  #     - "5040:5040"  # Expose the necessary port
  #   depends_on:
  #     - redis

volumes:
  pgdata: {}

networks:
  backend:
    driver: bridge